language: node_js
  node_js:
    - "8"

  branches:
    only:
      - master

  before_script:
    - cd FABI-Web
    - npm install -g @angular/cli

  script:
    - ng test --watch=false
    - ng build --prod --aot